---
name: Infra - dev

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


  repository_dispatch:
    types: [ dev ]

jobs:

  tfbackend:
    name: TF Backend - dev
    uses: ./.github/workflows/tfbackend.yml
    with:
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ vars.BACKEND_KEY_DEV }}
      region: ${{ vars.AWS_REGION }}
      filename: dev.s3.tfbackend

  tfvars:
    name: TF Variables - dev
    uses: ./.github/workflows/tfvars.yml
    with:
      bot-token-param: ${{ vars.BOT_TOKEN_PARAM_DEV }}
      secret-token-param: ${{ vars.SECRET_TOKEN_PARAM_DEV }}
      lambda-image-param: ${{ vars.BOT_WEBHOOK_IMAGE_PARAM_DEV }}

  tf-plan:
    name: TF Plan - dev
    needs: [ tfbackend, tfvars ]
    uses: ./.github/workflows/tf-plan.yml
    with:
      working-directory: ${{ vars.WORKDIR_DEV }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
      tfbackend: ${{ needs.tfbackend.outputs.filename }}
      tfvars: ${{ needs.tfvars.outputs.filename }}
      filename: dev.tfplan

  tf-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: TF Apply - dev
    needs: [ tfbackend, tfvars, tf-plan ]
    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: dev
      working-directory: ${{ vars.WORKDIR_DEV }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
      tfbackend: ${{ needs.tfbackend.outputs.filename }}
      tfvars: ${{ needs.tfvars.outputs.filename }}
      tfplan: ${{ needs.tf-plan.outputs.filename }}
