---
name: Infra

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:

  tfbackend:
    uses: ./.github/workflows/tfbackend.yml
    with:
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ vars.BACKEND_KEY_DEV }}
      region: ${{ vars.AWS_REGION }}

  tf_plan:
    name: TF Plan - dev
    runs-on: ubuntu-latest
    needs: tfbackend
    defaults:
      run:
        working-directory: ${{ vars.WORKDIR_LIVE }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-session-name: gh-actions
      #     role-to-assume: ${{ vars.IAM_ROLE_ARN }}
      #     aws-region: ${{ vars.AWS_REGION }}

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2

      - name: Check
        run: |
          echo ${{ needs.tfbackend.outputs.artifact }}
          echo ${{ needs.tfbackend.outputs.filename }}
