---
name: Infra - dev

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:

  tfbackend:
    name: TF Backend - dev
    uses: ./.github/workflows/tfbackend.yml
    with:
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ vars.BACKEND_KEY_DEV }}
      region: ${{ vars.AWS_REGION }}
      filename: dev.s3.tfbackend

  tfvars:
    name: TF Variables - dev
    uses: ./.github/workflows/tfvars.yml
    with:
      bot-token-param: $${{ vars.BOT_TOKEN_PARAM_DEV }}
      secret-token-param: $${{ vars.SECRET_TOKEN_PARAM_DEV }}
      lambda-image-param: $${{ vars.BOT_WEBHOOK_IMAGE_PARAM_DEV }}

  tf-plan:
    name: TF Plan - dev
    runs-on: ubuntu-latest
    needs: [ tfbackend, tfvars ]
    defaults:
      run:
        working-directory: ${{ vars.WORKDIR_DEV }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: gh-actions
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: TF Backend
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.tfbackend.outputs.filename }}
          path: ${{ vars.WORKDIR_DEV }}

      - name: TF Variables
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.tfvars.outputs.filename }}
          path: ${{ vars.WORKDIR_DEV }}

      - name: TF Init
        run: |
          terraform init -backend-config=${{ needs.tfbackend.outputs.filename }}

      - name: TF Plan
        run: |
          terraform plan -out=dev.tfplan

      - name: Save Plan
        uses: actions/upload-artifact@v3
        with:
          name: dev.tfplan
          path: ${{ vars.WORKDIR_DEV }}/dev.tfplan

  tf-apply:
    name: TF Apply - dev
    runs-on: ubuntu-latest
    needs: [ tfbackend, tfvars, tf-plan ]
    environment: dev
    defaults:
      run:
        working-directory: ${{ vars.WORKDIR_DEV }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: gh-actions
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: TF Backend
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.tfbackend.outputs.filename }}
          path: ${{ vars.WORKDIR_DEV }}

      - name: TF Variables
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.tfvars.outputs.filename }}
          path: ${{ vars.WORKDIR_DEV }}

      - name: TF Init
        run: |
          terraform init -backend-config=${{ needs.tfbackend.outputs.filename }}

      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: dev.tfplan
          path: ${{ vars.WORKDIR_DEV }}

      - name: TF Apply
        run: |
          terraform apply -auto-approve dev.tfplan
