---
name: Infra - live

permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  repository_dispatch:
    types: [ live-* ]

jobs:

  tfbackend:
    name: TF Backend - live
    uses: ./.github/workflows/tfbackend.yml
    with:
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ vars.BACKEND_KEY_LIVE }}
      region: ${{ vars.AWS_REGION }}
      filename: live.s3.tfbackend

  tfvars:
    name: TF Variables - live
    uses: ./.github/workflows/tfvars.yml
    with:
      bot-token-param: ${{ vars.BOT_TOKEN_PARAM_LIVE }}
      secret-token-param: ${{ vars.SECRET_TOKEN_PARAM_LIVE }}
      lambda-image-param: ${{ vars.BOT_WEBHOOK_IMAGE_PARAM_LIVE }}

  tf-plan:
    name: TF Plan - live
    needs: [ tfbackend, tfvars ]
    uses: ./.github/workflows/tf-plan.yml
    with:
      working-directory: ${{ vars.WORKDIR_LIVE }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
      tfbackend: ${{ needs.tfbackend.outputs.filename }}
      tfvars: ${{ needs.tfvars.outputs.filename }}
      filename: live.tfplan

  tf-apply:
    name: TF Apply - live
    needs: [ tfbackend, tfvars, tf-plan ]
    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: live
      working-directory: ${{ vars.WORKDIR_LIVE }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
      tfbackend: ${{ needs.tfbackend.outputs.filename }}
      tfvars: ${{ needs.tfvars.outputs.filename }}
      tfplan: ${{ needs.tf-plan.outputs.filename }}
