---
on:
  workflow_call:

    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      working-directory:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      tfbackend:
        required: false
        type: string
        default: this.s3.tfbackend
      tfvars:
        required: false
        type: string
        default: terraform.tfvars
      tfplan:
        required: false
        type: string
        default: this.tfplan

jobs:

  tf-apply:

    runs-on: ${{ inputs.runs-on }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: TF Bootstrap
        uses: ./.github/actions/tf-bootstrap
        with:
          working-directory: ${{ inputs.working-directory }}
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
          tfbackend: ${{ inputs.tfbackend }}
          tfvars: ${{ inputs.tfvars }}

      - name: Download ${{ inputs.tfplan }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tfplan }}
          path: ${{ inputs.working-directory }}

      - name: TF Apply - ${{ inputs.tfplan }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          terraform apply -auto-approve ${{ inputs.tfplan }}
